# Generated by Django 5.0.3 on 2024-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccounts_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='account_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
