# Generated by Django 5.0.3 on 2024-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccounts_id_alter_useraccounts_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='account_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='precurement_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
